### PR TITLE
Feature/uh 003 create client

### PR DESCRIPTION
**Pull request by TheHoodini**
Empty form design:

feature-uh-003-create-client exclusive-crm pages dev_clients_create

When not all the fields are filled the Create button is disabled.

Filled form design:

feature-uh-003-create-client exclusive-crm pages dev_clients_create (1)

When contacts are added:

image

Responsive design with contact:

feature-uh-003-create-client exclusive-crm pages dev_clients_create(iPhone 12 Pro)

Client added:

image

### CODE REVIEW

**Review by dgop92 — CHANGES_REQUESTED** [review]
look the internal messages

**Review by dgop92 — APPROVED** [review]
looks great, but code quality could better

**Review by AlejandroSalas1143 — APPROVED** [review]
good

**Review by sebastian0327 — APPROVED** [review]

**Review by ndelarans — APPROVED** [review]
ok

**Pull request merged**
